#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
#targetType=libso
#. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

set -x

./src/Allclean

wclean ./applications/utilities/preProcessing/canteraToFPVFoam-v1912
wclean ./applications/utilities/postProcessing/FPVFoamPost-v1912
wclean ./applications/solver/FPVFoam-v1912
wclean ./applications/solver/FPVBuoyantFoam-v1912

# ----------------------------------------------------------------- end-of-file
